fix Java compile error
(let (x) (null (setq x 1)))
-> compile error
/MurmelProgram.java:23: error: unexpected type
        return (((Object)args2[0] = 1L == (Object)null) ? _t : null);
                 ^
  required: variable
  found:    value
/MurmelProgram.java:23: error: incomparable types: long and Object
        return (((Object)args2[0] = 1L == (Object)null) ? _t : null);
                                       ^
2 errors